project_name: 50.002 Log Book
project_description: Documentation built with SkyDocs.
project_url: https://cyra-starling.github.io/50.002-Log-Book/

default_language: en
lunr_search: true
default_order_alphabetical: true